### PR TITLE
atman: Import FOD

### PR DESCRIPTION
**Pull request by AshutoshSundresh**
Accidentally removed by Xiaomi

What this commit does:
Import NoFlicker.lib reverse engineered from iPhone 11 image because It too has hidden FOD like violet

atman: sepolicy: Add FOD sepolicy imported from our pals at Realme https://github.com/realme-kernel-opensource/realme3pro-kernel-source/commit/66627abaa61c26aac5be972beb310ecd9949e1f0

### CODE REVIEW

**Comment by MezzLasha** [comment]
+1

**Comment by NitroFuN** [comment]
+1 will improve phone usage experience so much

**Comment by sashascurtu** [comment]
+1

**Review by ItsVixano — APPROVED** [review]
+1 , now fod is perfectly made for violet

**Pull request merged**
