### PR TITLE
MORE VOLTE FREE 100% LEGIT

### PR DESCRIPTION
**Pull request by ItsVixano**
ULTRA 🅱️OLTE implementation

### CODE REVIEW

**Comment by mashed-potatoes** [comment]
🅱️OLTE work confirmed 💯%

**Review by mashed-potatoes — APPROVED** [review]

**Comment by ender1324** [comment]
sepolicy implementation trash, needs fixes, everything else has the volte stamp of aproval

**Comment by ItsVixano** [comment]
> sepolicy implementation trash, needs fixes, everything else has the volte stamp of aproval

;_;

**Review by mashed-potatoes — APPROVED** [review]
Ok sur

**Comment by ender1324** [comment]
perfect sepolicy solution, never seen anything like this before

**Review by ender1324 — APPROVED** [review]

**Comment by mashed-potatoes** [comment]
image

**Pull request merged**
