### PR TITLE
how needs persist for gaming????????????

### PR DESCRIPTION
**Pull request by maade93791**
* useless partition for real gamers

### CODE REVIEW

**Comment by danascape** [comment]
gyro will die, sooooo

**Comment by Dyneteve** [comment]
@danascape Dosen't matter, the huge pro's gonna use the power of the mind to control in pubg merged

**Comment by Dyneteve** [comment]
also @danascape as they said

- Permissive is user choice
- Persist is also user choice

**Comment by danascape** [comment]
lmfao

**Pull request merged**
